### ISSUE TITLE
Open a Login Page First of template-drawer!

### ISSUE THREAD

**Issue by phantoxe** [NativeScript/template-drawer-navigation-ts#46]
Hi guys... i need help.

I created a LoginComponent and i need open this page first to make the Login and then go to FirstPage from this template.

My route is like this:

const routes: Routes = [
    { path: "", redirectTo: "/login", pathMatch: "full" },
    { path: "login", loadChildren: "./login/login.module#LoginModule" },
    { path: "profile", loadChildren: "./profile/profile.module#ProfileModule" },
    { path: "photos", loadChildren: "./photos/photos.module#PhotosModule" },
    { path: "videos", loadChildren: "./videos/videos.module#VideosModule" },
    { path: "reviews", loadChildren: "./reviews/reviews.module#ReviewsModule" },
    { path: "settings", loadChildren: "./settings/settings.module#SettingsModule" }
];

But when i run the APP... the login open correct... but have a HEADER on top of this page with the name of my app. And in inside of my .html i just have a simples label.

How can i remove the header?

**Comment by ADjenkov** [comment]
Hi @phantoxe, 

If I understand correctly, you want to hide the ActionBar from your Login page.
You can explicitly control the visibility of the ActionBar by setting the `actionBarHidden` property of the Page, look this:

```
import { Page } from "ui/page";

export class LoginComponent {
    constructor(page: Page) {
        page.actionBarHidden = true;
    }
}
```

However, note that https://github.com/NativeScript/template-drawer-navigation-ts/issues is not a general support channel -- you can use https://discourse.nativescript.org/ should you have further NativeScript inquiries.
