### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/template-drawer-navigation-ts#72]
I just created an new app using this template..

Would be possible for the .gitignore file to be copied across ?

**Comment by manoldonev** [comment]
@pedromorgan currently this is not implemented in the template preinstall/postinstall script logic but we will consider extending it as that would be useful addition to the getting started experience.

**Comment by manoldonev** [comment]
Feature is merged in the `master` branch of the templates' repos.
